# Generated by Django 4.0.1 on 2022-02-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseepisode',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
