# Generated by Django 4.0.1 on 2022-01-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0002_initial'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article_tags', to='cms.Tag'),
        ),
    ]
